### PR TITLE
New trip database

### PR DESCRIPTION
**Pull request by haclark30**
- Updated the NewTrip activity to use TextInputLayouts instead (look nicer and easier to deal with input errors)
- Error checking on NewTrip activity
- Implemented basic database using Room API along with a trip table. New Trip activity will save to the database. 
- Updated ListView on HomePage to just display text from first trip in database (just to test reading from db worked)

### CODE REVIEW

**Review by makpls — APPROVED** [review]
Nice! One thing of note, could you force txtEditDestination to be a single line? I think it would be nice if pressing enter moved you onto the next element rather than creating multiple lines.

**Comment by haclark30** [comment]
> Nice! One thing of note, could you force txtEditDestination to be a single line? I think it would be nice if pressing enter moved you onto the next element rather than creating multiple lines.

done!

**Comment by ndcahuang** [comment]
Correct me if I'm wrong, but should I expect to see anything being displayed in the list view?

**Comment by makpls** [comment]
> Correct me if I'm wrong, but should I expect to see anything being displayed in the list view?

The destination of the first place you enter should show up in the list view. Just the destination.

**Comment by haclark30** [comment]
> > Correct me if I'm wrong, but should I expect to see anything being displayed in the list view?
> 
> The destination of the first place you enter should show up in the list view. Just the destination.

Correct, and if you haven't added any trips yet, it should say "You don't have any trips". This was just to make sure reading from the db works.

**Review by ndcahuang — APPROVED** [review]
this works

**Pull request merged**
