### PR TITLE
Add layout

### PR DESCRIPTION
**Pull request by jabbarifard**
tag suggestion.

### CODE REVIEW

**Comment by LynetteGao** [comment]
Your code seems not working for me and it shows nothing on the screen... can somebody else look at it? @haclark30 @ndcahuang @makpls

**Comment by makpls** [comment]
> Your code seems not working for me and it shows nothing on the screen... can somebody else look at it? @haclark30 @ndcahuang @makpls

I'm resolving the conflicts now

**Comment by haclark30** [comment]
A few things:
1. Your activity is called activity_main. You should be naming it something to do with Tag Suggestion.
2. The tags should be implemented in some scrollable view so that we can scroll through a bunch of them. There will be more than the 6 we mentioned in the wireframes, right?

**Review by makpls — DISMISSED** [review]
There's really no point having static images right now; rather, could you implement a rudimentary "recyclerView" object?

Also I changed a little bit just to make it work, please VCS->Git->Fetch to update your local copy

**Comment by haclark30** [comment]
A couple things on style and naming things:
- Classes should always be named with PascalCase, so your tagsuggestion class should be TagSuggestion
- Make sure to change the IDs of the views to something descriptive. textView1 is not descriptive and will be very confusing as the codebase grows

For renaming items that you have already referenced elsewhere, right-click the name, select "Refactor", and then "Rename". Android Studio will then help renaming it everywhere else.

Also, I don't see a way to actually view the activity in the app, so I can't see what it actually looks like when rendered.

**Review by haclark30 — APPROVED** [review]
Fixed merge conflicts, we are good to go on this now

**Review by ndcahuang — APPROVED** [review]

**Pull request merged**
